[Info]
Name=Buff 数显设置
DescShort=Buff 数显设置
DescLong=特定 Buff 所需的数显设置
[Register]
****=DigitalSetting
[****]
#DisplayType=Hexagon
#Owner=All
#Observer=yes
#Show.Signs=yes
#Show.Value=yes
#Show.Max=yes
#Show.Min=no
#Show.Addon=no
#Show.Percent=no
#Show.Bars=yes
#Show.BarBuffers=yes
#DirectionType=Right
#HorizontalAlign=Left
#HorizontalAlign.Signs=Right
#HorizontalAlign.Bars=Center
#VerticalAlign=Center
#VerticalAlign.Signs=Center
#VerticalAlign.Bars=Center
#ColumnType=Left
#BasePositionFilp=no,no
#PixelSelectionBracketDelta=yes
#Offset=0,0
#Offset.Signs=0,0
#Offset.Signs.Background=0,0
#Offset.Bars=0,0
#Offset.Bars.Background=0,0
#Size=0,0
#Size.Signs=0,9
#Size.Bars=2,4
#Count.BarPips=0
Spacing.Bars=5
Shp.Signs11=SIDigitals_CYellow
Spacing.Separators=0,0
Condition5=0.792
Brackets.Value=-1,-1
Condition6=0.75
Condition16=0.333
Shp.Signs4=SIDigitals_CGreen
Condition18=0.25
Shp.Bars23=SIDigitals_BYellow
Shp.Signs21=SIDigitals_CRed
Condition10=0.583
Signs.Value=-1
Brackets.Max=-1,-1
Condition11=0.542
Shp.Signs13=SIDigitals_CGreen
Shp.Signs16=SIDigitals_CGreen
Shp.Bars4=SIDigitals_BGreen
Shp.Bars0=SIDigitals_BFull
Shp.Signs1=SIDigitals_CGreen
Shp.Bars10=SIDigitals_BGreen
Shp.Signs20=SIDigitals_CYellow
Condition21=0.125
Condition7=0.708
ConditionCount=24
Condition8=0.667
Condition3=0.875
Spacing.Signs=4
Shp.Signs15=SIDigitals_CRed
Signs.Min=-1
Shp.Bars22=SIDigitals_BGreen
Shp.Signs5=SIDigitals_CYellow
Shp.Bars1=SIDigitals_BGreen
Shp.Signs6=SIDigitals_CRed
Shp.Bars17=SIDigitals_BYellow
Separators.Addon=15
Shp.Signs9=SIDigitals_CRed
Shp.Signs22=SIDigitals_CGreen
Condition9=0.625
Shp.Bars11=SIDigitals_BYellow
Shp.Bars13=SIDigitals_BGreen
Condition14=0.417
Brackets.Addon=-1,-1
Condition1=0.958
Condition12=0.5
Shp.Signs17=SIDigitals_CYellow
Shp.Bars14=SIDigitals_BYellow
Shp.Signs24=SIDigitals_CRed
Spacing.BarPips=-2
Shp.Signs23=SIDigitals_CYellow
Shp.Bars16=SIDigitals_BGreen
Separators.Value=-1
Shp.Bars5=SIDigitals_BYellow
Separators.Min=15
Shp.Signs8=SIDigitals_CYellow
Shp.Bars21=SIDigitals_BRed
Shp.Bars8=SIDigitals_BYellow
Condition20=0.167
Condition4=0.833
Signs.Max=-1
Shp.Signs18=SIDigitals_CRed
Condition17=0.292
Shp.Bars24=SIDigitals_BRed
Brackets.Min=-1,-1
Shp.Bars3=SIDigitals_BRed
Spacing.Brackets=0,0
CustomCondition=yes
Condition2=0.917
Shp.Bars7=SIDigitals_BGreen
Shp.Bars6=SIDigitals_BRed
Separators.Max=15
Shp.Signs10=SIDigitals_CGreen
Shp.Bars2=SIDigitals_BYellow
Shp.Bars9=SIDigitals_BRed
Condition13=0.458
Shp.Signs2=SIDigitals_CYellow
Condition23=0.042
Condition19=0.208
Signs.Addon=-1
Condition15=0.375
Condition22=0.083
Condition0=1
Shp.Signs12=SIDigitals_CRed
Shp.Bars15=SIDigitals_BRed
Shp.Signs3=SIDigitals_CRed
Shp.Bars20=SIDigitals_BYellow
Shp.Bars12=SIDigitals_BRed
Shp.Signs19=SIDigitals_CGreen
Pal=SIDigitals
Shp.Signs0=SIDigitals_CFull
Shp.Signs14=SIDigitals_CYellow
Shp.Bars19=SIDigitals_BGreen
Shp.Signs7=SIDigitals_CGreen
Shp.Bars18=SIDigitals_BRed