[Info]
Name=2.按钮语句包
DescShort=按钮语句包
DescLong=包含各种按钮设置
[Register]
****=FlagPack
[****]
Digital=yes
#Digital.Button=                                 ; 按钮显示设置 , 显示按钮 , 这是一个进行了特殊优化的【数值显示设置】 , 大部分【血条】相关的属性都彼此通用 , 不设置不显示 , 默认值是 空
#Digital.Button.KeyBinds=                        ; 按钮绑定列表 , 有几个按钮写几个绑定 , 不写的算不绑定 , 详细情况请见【空白快捷键】部分
                                                ; 可用值 : 1 - 12 = 第 1 个到第 12 个【空白快捷键】 , 0 或其他值 = 无绑定 (建议写 0) , 默认值是 0
#Digital.Button.Owner=Self                       ; 作战方归属 , 谁可以通过绑定的【空白快捷键】点击按钮
                                                ; 可用值 : All (无简写) , Self | S , Allies | A , Enemies | E , Neutral | N , 默认值是 Self (不区分大小写)
                                                ; 当需要匹配多种作战方时 , 多个值之间使用 "," 字符连接即可 , 栗如同时匹配己方和敌方 : Self,Enemies 或 S,E (简写可以混用 , 不要有空格)
#Digital.Button.Observer=no                      ; yes/no , 观察者是否可以通过绑定的【空白快捷键】点击按钮 , 默认值是 no
#Digital.AutoOffset=yes                          ; yes/no , 是否会根据 Buff 的 Order 属性自动偏移 , 从而避免显示的数值和其他 Buff 重叠在一起 , 偏移的高度由【数值显示设置】的 Size 属性决定 , 默认值是 yes
#Digital.Cameos.Pcx=                             ; 文件名列表 , 需要显示的图标文件名 (包括后缀) , 默认值是 空