[Info]
Name=2.数显语句包
DescShort=数显语句包
DescLong=包含各种数显设置
[Register]
****=WICDigitalFlagPack
[****]
Digital=yes                                      ; yes/no , 是否启用数值显示 , 默认值是 no
#Digital.Primary=                                ; 数值显示设置 , 显示第 1 类数值 (显示哪些数值请见具体的 Buff 效果) , 不设置不显示 , 默认值是 空
#Digital.Secondary=                              ; 数值显示设置 , 显示第 2 类数值 (显示哪些数值请见具体的 Buff 效果) , 不设置不显示 , 默认值是 空
#Digital.Tertiary=                               ; 数值显示设置 , 显示第 3 类数值 (显示哪些数值请见具体的 Buff 效果) , 不设置不显示 , 默认值是 空
#Digital.Quaternary=
#Digital.AutoOffset=yes                          ; yes/no , 是否会根据 Buff 的 Order 属性自动偏移 , 从而避免显示的数值和其他 Buff 重叠在一起 , 偏移的高度由【数值显示设置】的 Size 属性决定 , 默认值是 yes
#Digital.BufferSpeed=0.005                       ; 浮点数 , 【血条】的缓冲残影的消失速度 (对【按钮】无效) , 速度是每帧减少的百分比 , 0.005 意味着每帧减少 0.5% , 200 帧会掉空 , 默认值是 0.005 , 单位 : 比例/帧