[Info]
Name=投放单位
DescShort=投放单位 <主动>
DescLong=以单位所在位置为原点创建随机单位，建筑步兵载具飞机都行，如果目标位置被占据了，则会在旁边创建
[Register]
****0=WICBuffType
****1=DataPackTypes
****2=PackTypes.TechnoData
****3=PackTypes.ScriptData
****4=PackTypes.OffsetData
****5=PackTypes.AnimData
[****0]
#Effect.Type=Team
#TeamBuff=,****1,-1,0,yes,0
[****1]
#TechnoPacks=****2
#ScriptPacks=****3
#OffsetPacks=****4
#AnimPacks=****5
#TeamDataPackTheseBuffs=
#TeamDataPackThoseBuffs=
#Single=yes
#EffectRange=3
[****2]
#TeamTechnoDataTechno=
#Total=1
[****3]
[****4]
[****5]