;INI织网者 V1.0.9
;这是一个生成模块的样板
;生成于 2026年04月03日 星期五 15:08:11

[Info]
Name=投放单位
DescShort=投放单位 <主动>
DescLong=以单位所在位置为原点创建随机单位，建筑步兵载具飞机都行，如果目标位置被占据了，则会在旁边创建



[Register]
Rules#****0 = WICBuffType
Rules#****1 = DataPackTypes
Rules#****2 = PackTypes.TechnoData
Rules#****3 = PackTypes.ScriptData
Rules#****4 = PackTypes.AnimData
Rules#****5 = PackTypes.AnimData
Rules#****6 = PackTypes.TechnoData
Rules#****7 = PackTypes.OffsetData
Rules#****8 = 编组
Rules#****9 = 编组


Rules#[****0]
DisplayName#Prop = WIC Buff1
ImportDeltaX = -33.678337
ImportDeltaY = -3.068095
_InitialSecName#Var = ****0
_Local_Category#Var = WICBuffType
#Effect.Type = Team
#TeamBuff = ,****1,-1,0,yes,0
AresInherit = 


Rules#[****1]
DisplayName#Prop = WIC 数据包类型1
ImportDeltaX = -16.306540
ImportDeltaY = -3.132199
_InitialSecName#Var = ****1
_Local_Category#Var = DataPackTypes
#TechnoPacks = ****2,****6
#ScriptPacks = ****3
#OffsetPacks = ****7
#AnimPacks = ****4,****5
#TeamDataPackTheseBuffs = ,
#TeamDataPackThoseBuffs = ,
#Single = yes
#EffectRange = 3
AresInherit = 


Rules#[****2]
DisplayName#Prop = WIC 单位数据集合1
ImportDeltaX = 0.644352
ImportDeltaY = -8.378915
_InitialSecName#Var = ****2
_Local_Category#Var = PackTypes.TechnoData
Included#Prop = Rules, ****8
#TeamTechnoDataTechno1 = ,,
#Total = 1
AresInherit = 


Rules#[****3]
DisplayName#Prop = WIC 脚本数据集合1
ImportDeltaX = 1.061016
ImportDeltaY = -0.647433
_InitialSecName#Var = ****3
_Local_Category#Var = PackTypes.ScriptData
Included#Prop = Rules, ****8
#TeamScriptDataScript = ,,
#ScriptDataMission = 
AresInherit = 


Rules#[****4]
DisplayName#Prop = WIC 动画数据集合1
ImportDeltaX = 1.570278
ImportDeltaY = 7.917381
_InitialSecName#Var = ****4
_Local_Category#Var = PackTypes.AnimData
Included#Prop = Rules, ****8
#TeamAnimData1 = ,
AresInherit = 


Rules#[****5]
DisplayName#Prop = WIC 动画数据集合2
ImportDeltaX = 1.662871
ImportDeltaY = 12.454418
_InitialSecName#Var = ****5
_Local_Category#Var = PackTypes.AnimData
Included#Prop = Rules, ****8
#TeamAnimData2 = ,
AresInherit = 


Rules#[****6]
DisplayName#Prop = WIC 单位数据集合2
ImportDeltaX = 19.712326
ImportDeltaY = 8.873446
_InitialSecName#Var = ****6
_Local_Category#Var = PackTypes.TechnoData
Included#Prop = Rules, ****9
#TeamTechnoDataTechno2 = ,
#TeamTechnoDataTarget = ,
AresInherit = 


Rules#[****7]
DisplayName#Prop = WIC 偏移数据集合1
ImportDeltaX = 21.084877
ImportDeltaY = 17.696974
_InitialSecName#Var = ****7
_Local_Category#Var = PackTypes.OffsetData
Included#Prop = Rules, ****9
#OffsetData = ,,,,
AresInherit = 


Rules#[****8]
DisplayName#Prop = 编组
ImportDeltaX = 1.021011
ImportDeltaY = -2.975454
_InitialSecName#Var = ****8
Including#Prop = Rules, ****2
Including#Prop = Rules, ****3
Including#Prop = Rules, ****4
Including#Prop = Rules, ****5


Rules#[****9]
DisplayName#Prop = 编组_1
ImportDeltaX = 18.244738
ImportDeltaY = -2.939892
_InitialSecName#Var = ****9
Including#Prop = Rules, ****6
Including#Prop = Rules, ****7


