[Info]
Name=Buff 按钮设置
DescShort=Buff 按钮设置
DescLong=特定 Buff 所需的按钮设置
[Register]
****=ButtonSetting
[****]
#DisplayType=Default
#Owner=Self
#Observer=no
#Show.Signs=yes
#Show.Bars=yes
#Show.BarBuffers=yes
#ProcessFrameCount=30
#PrintColor.Text=225,225,40
#PrintColor.TextBackground=4,4,4
Pal=SIDigitalButtons
Shps.Bars=
Shp.Bars.Full=SIDigitalButtons_BFull
Shp.Bars.Green=SIDigitalButtons_BGreen
Shp.Bars.Yellow=SIDigitalButtons_BYellow
Shp.Bars.Red=SIDigitalButtons_BRed
Shp.Bars.Background=
Shp.Bars.Process=SIDigitalButtons_BProcess
#HorizontalAlign=Center
#VerticalAlign=Center
#ColumnType=Center
#BasePositionFilp=no,no
#PixelSelectionBracketDelta=yes
#Offset=0,0
#Offset.Bars=0,0
#Offset.Bars.Background=0,0
#Spacing.BarPips=60
Size=60,48
Size.Bars=60,48
Count.BarPips=1
Click.Owner=Self
Click.Observer=no