[Info]
Name=WICTestBuff
DescShort=WICTestBuff
DescLong=由艾木魁亲手撰写的第一个有效Buff模块。新语句见RegisterTypesWIC，TypeAltWIC文件。
[Register]
****=WICBuff
[****]
#订单上限=
#FactoryMatrix1=
#FactoryMatrix2=
#Buff.Counts=114514
Effect.Type=Factory
